### ISSUE TITLE
api expired ????

### ISSUE THREAD

**Issue by jordibonastrem** [primal100/pybitcointools#38]
hi i get this when trying to get wallet outputs:

`Exception('{"status":"fail","data":{"error_message":"API Key invalid, account access expired, or this account\'s daily request limit has been exhausted."}}')`

**Comment by bakd247** [comment]
I do not manage this library…I just forked it because it was not being managed any longer….
you might want to give pycoin a try until I get a chance to figure out whats going on with the pybitcointools...sorry for that

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Jordi ***@***.***>
Sent: Tuesday, January 24, 2023 8:44 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [primal100/pybitcointools] api expired ???? (Issue #38)


hi i get this when trying to get wallet outputs:

**Comment by primal100** [comment]
Hi, I finally got around to maintaining the library again and made a new PR with tons of changes including a move to ElectrumX servers. Please try out the latest version on Pypi (2.0.4) and let me know if this is solved.
